// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Books.API.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20240529045821_BooksSeedMigration")]
    partial class BooksSeedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Books.API.DataAccess.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Erin Morgenstern",
                            Description = "Written in rich, seductive prose, this spell-casting novel is a feast for the senses and the heart.",
                            Genre = "fiction",
                            Language = "English",
                            Pages = 506,
                            Title = "The Night Circus",
                            Year = 2011
                        },
                        new
                        {
                            Id = 2,
                            Author = "Anthony Doer",
                            Description = "When everything is lost, it’s our stories that survive.",
                            Genre = "fiction",
                            Language = "English",
                            Pages = 626,
                            Title = "Cloud Cuckoo Land",
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
